# _config.yml
title: Data Science Portfolio by Hypatia Hou
description: A showcase of my lifescience analytics or AI/ML projects.
author: Your Name
url: "https://hypatia-dev.github.io"
github_username: hypatia-dev
markdown: kramdown
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme